-- OakBoard MySQL schema
-- Compatible target: MySQL 8.0+ or MariaDB 10.6+.
-- IDs are generated by the application as UUID strings.

SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS app_users (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  email VARCHAR(320) NOT NULL,
  full_name VARCHAR(160) NOT NULL DEFAULT '',
  email_verified_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY app_users_email_unique (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS onboarding_imports (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  owner_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  source_type ENUM('email_text', 'pdf_text', 'notebooklm_text', 'manual_text') NOT NULL,
  source_filename VARCHAR(512) NULL,
  raw_text LONGTEXT NOT NULL,
  parser_provider VARCHAR(100) NOT NULL DEFAULT 'manual',
  parser_model VARCHAR(160) NULL,
  preferred_weeks TINYINT UNSIGNED NULL,
  parsed_json JSON NULL,
  status ENUM('draft', 'parsed', 'applied', 'failed') NOT NULL DEFAULT 'draft',
  error_message TEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY onboarding_imports_owner_created_idx (owner_id, created_at),
  CONSTRAINT onboarding_imports_owner_fk
    FOREIGN KEY (owner_id) REFERENCES app_users(id) ON DELETE CASCADE,
  CONSTRAINT onboarding_imports_weeks_chk
    CHECK (preferred_weeks IS NULL OR preferred_weeks IN (2, 4))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS onboarding_plans (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  owner_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  title VARCHAR(255) NOT NULL DEFAULT 'Onboarding Plan',
  role VARCHAR(160) NOT NULL DEFAULT '',
  reports_to VARCHAR(160) NOT NULL DEFAULT '',
  collaborates_with VARCHAR(255) NOT NULL DEFAULT '',
  duration_weeks TINYINT UNSIGNED NOT NULL,
  plan_json JSON NOT NULL,
  source_import_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  archived_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY onboarding_plans_owner_created_idx (owner_id, created_at),
  KEY onboarding_plans_owner_active_idx (owner_id, archived_at, updated_at),
  KEY onboarding_plans_source_import_idx (source_import_id),
  CONSTRAINT onboarding_plans_owner_fk
    FOREIGN KEY (owner_id) REFERENCES app_users(id) ON DELETE CASCADE,
  CONSTRAINT onboarding_plans_source_import_fk
    FOREIGN KEY (source_import_id) REFERENCES onboarding_imports(id) ON DELETE SET NULL,
  CONSTRAINT onboarding_plans_duration_chk
    CHECK (duration_weeks IN (2, 4))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS onboarding_email_logs (
  id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  owner_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  plan_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  recipient_email VARCHAR(320) NOT NULL,
  cc_email VARCHAR(320) NULL,
  provider VARCHAR(100) NOT NULL DEFAULT 'resend',
  provider_message_id VARCHAR(255) NULL,
  status ENUM('sent', 'failed') NOT NULL,
  error_message TEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY onboarding_email_logs_owner_created_idx (owner_id, created_at),
  KEY onboarding_email_logs_plan_idx (plan_id),
  CONSTRAINT onboarding_email_logs_owner_fk
    FOREIGN KEY (owner_id) REFERENCES app_users(id) ON DELETE CASCADE,
  CONSTRAINT onboarding_email_logs_plan_fk
    FOREIGN KEY (plan_id) REFERENCES onboarding_plans(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
